"""Subclass of Dialog_FuzzAlreadyMinimized, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_FuzzAlreadyMinimized
class FuzzingTool_Dialog_FuzzAlreadyMinimized( FuzzingTool.Dialog_FuzzAlreadyMinimized ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_FuzzAlreadyMinimized.__init__( self, parent )

	# Handlers for Dialog_FuzzAlreadyMinimized events.
	def Button_OKOnButtonClick( self, event ):
		# TODO: Implement Button_OKOnButtonClick
		pass


