"""Subclass of Frame_StartupScreen, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Frame_StartupScreen
class FuzzingTool_Frame_StartupScreen( FuzzingTool.Frame_StartupScreen ):
	def __init__( self, parent ):
		FuzzingTool.Frame_StartupScreen.__init__( self, parent )

	# Handlers for Frame_StartupScreen events.
	def Frame_StartupScreenOnClose( self, event ):
		# TODO: Implement Frame_StartupScreenOnClose
		pass

	def MenuItem_StartFuzzingOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_StartFuzzingOnMenuSelection
		pass

	def MenuItem_StopFuzzingOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_StopFuzzingOnMenuSelection
		pass

	def MenuItem_TextFormStringOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_TextFormStringOnMenuSelection
		pass

	def MenuItem_TextFormBytesOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_TextFormBytesOnMenuSelection
		pass

	def MenuItem_PathFormRelativeOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_PathFormRelativeOnMenuSelection
		pass

	def MenuItem_MinimizeFuzzOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_MinimizeFuzzOnMenuSelection
		pass

	def MenuItem_InputTestcaseandRunOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_InputTestcaseandRunOnMenuSelection
		pass

	def MenuItem_SBFLOnMenuSelection( self, event ):
		# TODO: Implement MenuItem_SBFLOnMenuSelection
		pass

	def Grid_TestcasesOnGridLabelLeftClick( self, event ):
		# TODO: Implement Grid_TestcasesOnGridLabelLeftClick
		pass


