"""Subclass of Dialog_InputChoose, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_InputChoose
class FuzzingTool_Dialog_InputChoose( FuzzingTool.Dialog_InputChoose ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_InputChoose.__init__( self, parent )

	# Handlers for Dialog_InputChoose events.
	def DirPicker_ChooseInputOnDirChanged( self, event ):
		# TODO: Implement DirPicker_ChooseInputOnDirChanged
		pass

	def bSizer_OKorCancelOnCancelButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnCancelButtonClick
		pass

	def bSizer_OKorCancelOnOKButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnOKButtonClick
		pass


