"""Subclass of Dialog_ErrorLog, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_ErrorLog
class FuzzingTool_Dialog_ErrorLog( FuzzingTool.Dialog_ErrorLog ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_ErrorLog.__init__( self, parent )

	# Handlers for Dialog_ErrorLog events.
	def Button_OKOnButtonClick( self, event ):
		# TODO: Implement Button_OKOnButtonClick
		pass


