"""Subclass of Dialog_ProgramChoose, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_ProgramChoose import FuzzingTool_Dialog_ProgramChoose

# Implementing Dialog_ProgramChoose
class FuzzingTool_Dialog_ProgramChoose_Child( FuzzingTool_Dialog_ProgramChoose ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_ProgramChoose.__init__( self, parent )
		self.bSizer_OKorCancelOK.Disable()
		self.program=""

	# Handlers for Dialog_ProgramChoose events.
	def FilePicker_ChooseProgramOnFileChanged( self, event ):
		# TODO: Implement FilePicker_ChooseProgramOnFileChanged
		self.bSizer_OKorCancelOK.Enable()

	# Handlers for Dialog_ProgramChoose events.
	def bSizer_OKorCancelOnCancelButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnCancelButtonClick
		self.EndModal(False)
		
	def bSizer_OKorCancelOnOKButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnOKButtonClick
		self.program=self.FilePicker_ChooseProgram.GetPath()
		self.EndModal(True)

