"""Subclass of Dialog_GrammarReduceError, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_GrammarReduceError import FuzzingTool_Dialog_GrammarReduceError

# Implementing Dialog_GrammarReduceError
class FuzzingTool_Dialog_GrammarReduceError_Child( FuzzingTool.Dialog_GrammarReduceError ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_GrammarReduceError.__init__( self, parent )

	# Handlers for Dialog_GrammarReduceError events.
	def Button_OKOnButtonClick( self, event ):
		# TODO: Implement Button_OKOnButtonClick
		self.EndModal(True)


