"""Subclass of Dialog_AskStopFuzzing, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_AskStopFuzzing import FuzzingTool_Dialog_AskStopFuzzing

# Implementing Dialog_AskStopFuzzing
class FuzzingTool_Dialog_AskStopFuzzing_Child( FuzzingTool_Dialog_AskStopFuzzing ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_AskStopFuzzing.__init__( self, parent )

	# Handlers for Dialog_AskStopFuzzing events.
	def bSizer_YesorNoOnNoButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnNoButtonClick
		self.EndModal(False)

	def bSizer_YesorNoOnYesButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnYesButtonClick
		self.EndModal(True)


