"""Subclass of Dialog_CompileforAFLCommand, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_CompileforAFLCommand import FuzzingTool_Dialog_CompileforAFLCommand

# Implementing Dialog_CompileforAFLCommand
class FuzzingTool_Dialog_CompileforAFLCommand_Child( FuzzingTool_Dialog_CompileforAFLCommand ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_CompileforAFLCommand.__init__( self, parent )

	# Handlers for Dialog_CompileforAFLCommand events.
	def Button_OKOnButtonClick( self, event ):
		# TODO: Implement Button_OKOnButtonClick
		#self.Close()
		self.EndModal(True)


