"""Subclass of Dialog_AskCompileforAFL, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_AskCompileforAFL
class FuzzingTool_Dialog_AskCompileforAFL( FuzzingTool.Dialog_AskCompileforAFL ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_AskCompileforAFL.__init__( self, parent )

	# Handlers for Dialog_AskCompileforAFL events.
	def bSizer_YesorNoOnNoButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnNoButtonClick
		pass

	def bSizer_YesorNoOnYesButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnYesButtonClick
		pass


