"""Subclass of Dialog_MinimizeFuzz, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_MinimizeFuzz import FuzzingTool_Dialog_MinimizeFuzz
from DDtry import TryDeltaDebugging
import os
import subprocess

# Implementing Dialog_MinimizeFuzz
class FuzzingTool_Dialog_MinimizeFuzz_Child( FuzzingTool_Dialog_MinimizeFuzz ):
	def __init__( self, parent, program, fuzz):
		FuzzingTool.Dialog_MinimizeFuzz.__init__( self, parent )
		self.program=program
		self.fuzz=fuzz
		self.Text_ChoisedFuzz.SetLabel("Fuzz you selected: "+self.fuzz)
		self.DoLayoutAdaptation()

	# Handlers for Dialog_MinimizeFuzz events.
	def bSizer_YesorNoOnNoButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnNoButtonClick
		self.EndModal(False)

	def bSizer_YesorNoOnYesButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnYesButtonClick
		self.bSizer_YesorNoYes.Enable(False)
		self.bSizer_YesorNoNo.Enable(False)
		timeout=self.spinCtrlDouble_timeout.GetValue()
		if timeout==0:
			timeout=None
		dd=TryDeltaDebugging(program=self.program,input=self.fuzz,timeout=timeout)
		dd.DeltaDebug()
		dd.Out(dir="./reduced_testcases",filename=os.path.basename(self.fuzz)+"_min")
		self.minimizedfuzz=os.getcwd()+"/reduced_testcases/"+os.path.basename(self.fuzz)+"_min"
		self.EndModal(True)


