"""Subclass of Dialog_ProgramChoose, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_ProgramChoose
class FuzzingTool_Dialog_ProgramChoose( FuzzingTool.Dialog_ProgramChoose ):
	def __init__( self, parent ):
		print("Hi")
		FuzzingTool.Dialog_ProgramChoose.__init__( self, parent )

	# Handlers for Dialog_ProgramChoose events.
	def FilePicker_ChooseProgramOnFileChanged( self, event ):
		# TODO: Implement FilePicker_ChooseProgramOnFileChanged
		pass

	def bSizer_OKorCancelOnCancelButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnCancelButtonClick
		pass

	def bSizer_OKorCancelOnOKButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnOKButtonClick
		pass


