"""Subclass of Dialog_AskCompileforAFL, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_AskCompileforAFL import FuzzingTool_Dialog_AskCompileforAFL

# Implementing Dialog_AskCompileforAFL
class FuzzingTool_Dialog_AskCompileforAFL_Child( FuzzingTool_Dialog_AskCompileforAFL ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_AskCompileforAFL.__init__( self, parent )

	# Handlers for Dialog_AskCompileforAFL events.
	def bSizer_YesorNoOnNoButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnNoButtonClick
		self.EndModal(False)

	def bSizer_YesorNoOnYesButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnYesButtonClick
		self.EndModal(True)


