"""Subclass of Dialog_InputChoose, which is generated by wxFormBuilder."""

import wx
import FuzzingTool
from FuzzingTool_Dialog_InputChoose import FuzzingTool_Dialog_InputChoose

# Implementing Dialog_InputChoose
class FuzzingTool_Dialog_InputChoose_Child( FuzzingTool_Dialog_InputChoose ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_InputChoose.__init__( self, parent )
		self.input_path=""
		
	# Handlers for Dialog_InputChoose events.
	def bSizer_OKorCancelOnCancelButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnCancelButtonClick
		self.EndModal(False)

	def bSizer_OKorCancelOnOKButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnOKButtonClick
		self.input_path=self.DirPicker_ChooseInput.GetPath()
		self.EndModal(True)

