"""Subclass of Dialog_CompileforAFLCommand, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_CompileforAFLCommand
class FuzzingTool_Dialog_CompileforAFLCommand( FuzzingTool.Dialog_CompileforAFLCommand ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_CompileforAFLCommand.__init__( self, parent )

	# Handlers for Dialog_CompileforAFLCommand events.
	def Button_OKOnButtonClick( self, event ):
		# TODO: Implement Button_OKOnButtonClick
		pass


