"""Subclass of Dialog_InputTestcaseandRun, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_InputTestcaseandRun
class FuzzingTool_Dialog_InputTestcaseandRun( FuzzingTool.Dialog_InputTestcaseandRun ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_InputTestcaseandRun.__init__( self, parent )

	# Handlers for Dialog_InputTestcaseandRun events.
	def Button_CopyOnButtonClick( self, event ):
		# TODO: Implement Button_CopyOnButtonClick
		pass

	def CheckBox_UseGDBorNotOnCheckBox( self, event ):
		# TODO: Implement CheckBox_UseGDBorNotOnCheckBox
		pass

	def RadioBtn_CrashTestcaseOnRadioButton( self, event ):
		# TODO: Implement RadioBtn_CrashTestcaseOnRadioButton
		pass

	def RadioBtn_OriginalTestcaseOnRadioButton( self, event ):
		# TODO: Implement RadioBtn_OriginalTestcaseOnRadioButton
		pass

	def RadioBtn_MinimizedTestcaseOnRadioButton( self, event ):
		# TODO: Implement RadioBtn_MinimizedTestcaseOnRadioButton
		pass

	def Button_RunGDBOnButtonClick( self, event ):
		# TODO: Implement Button_RunGDBOnButtonClick
		pass

	def Button_ExitOnButtonClick( self, event ):
		# TODO: Implement Button_ExitOnButtonClick
		pass


