"""Subclass of Dialog_MinimizeFuzz, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_MinimizeFuzz
class FuzzingTool_Dialog_MinimizeFuzz( FuzzingTool.Dialog_MinimizeFuzz ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_MinimizeFuzz.__init__( self, parent )

	# Handlers for Dialog_MinimizeFuzz events.
	def checkBox_GrammarReduceOnCheckBox( self, event ):
		# TODO: Implement checkBox_GrammarReduceOnCheckBox
		pass

	def FilePicker_GrammarFileOnFileChanged( self, event ):
		# TODO: Implement FilePicker_GrammarFileOnFileChanged
		pass

	def bSizer_YesorNoOnNoButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnNoButtonClick
		pass

	def bSizer_YesorNoOnYesButtonClick( self, event ):
		# TODO: Implement bSizer_YesorNoOnYesButtonClick
		pass


