"""Subclass of Dialog_AskStartFuzzing, which is generated by wxFormBuilder."""

import wx
import FuzzingTool

# Implementing Dialog_AskStartFuzzing
class FuzzingTool_Dialog_AskStartFuzzing( FuzzingTool.Dialog_AskStartFuzzing ):
	def __init__( self, parent ):
		FuzzingTool.Dialog_AskStartFuzzing.__init__( self, parent )

	# Handlers for Dialog_AskStartFuzzing events.
	def bSizer_OKorCancelOnCancelButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnCancelButtonClick
		pass

	def bSizer_OKorCancelOnOKButtonClick( self, event ):
		# TODO: Implement bSizer_OKorCancelOnOKButtonClick
		pass


